---
- name: Create docker user group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add users to the docker user group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: Reset ssh connection to apply user changes
  become: true
  ansible.builtin.meta: reset_connection
