---
- name: Unlock docker plugin versions
  become: true
  community.general.yum_versionlock:
    name: "{{ docker_plugins }}"
    state: absent

- name: Install docker plugins - latest version
  become: true
  ansible.builtin.yum:
    name: "{{ docker_plugins }}"
    state: latest # noqa: package-latest
    update_cache: true
  notify: Restart docker

- name: Lock docker plugin versions
  become: true
  community.general.yum_versionlock:
    name: "{{ docker_plugins }}"
    state: present
